<?php

namespace tests\unit\services\siteCreator;

use app\services\siteCreator\ContentAnalyzer;

class ContentAnalyzerTest extends \Codeception\Test\Unit
{
    /**
     * @var ContentAnalyzer
     */
    private $contentAnalyzer;

    protected function setUp()
    {
        $this->contentAnalyzer = \Yii::$container->get(ContentAnalyzer::class);
        return parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testAnalyze(): void
    {
        $result = $this->contentAnalyzer->cleanFromLongWords('many text here another many text here manyPeople likeCamelCaseD words BrrrAaaH USSR LLLLove LLLLoveMe and here many text here');
        $this->assertEquals('many text here another many text here many people like camel caseD words brrr aaaH USSR LLLLove LLLlove me and here many text here', $result);
    }

    /**
     * @dataProvider textsVariants
     * @param string $text
     * @param bool $isEnglish
     */
    public function testCheckContentIsNotEnglish(string $text, bool $isEnglish): void
    {
        $result = $this->contentAnalyzer->checkContentIsEnglish($text);
        $this->assertEquals($isEnglish, $result);
    }

    public function textsVariants(): array
    {
        return [
            ['привет дядя федор groovy', false],
            ['hello mr jack', true],
            ['hello mr jack я Вася', false],
            ['привет, я пузырь', false],
            ['many many people loves иван because he\'s famous brraaaah', true]
        ];
    }
}